name: generate-docker-image
on: 
  #workflowを手動で実行
  workflow_despatch:

jobs:
  node-docker:
    - name: Checkout
      uses: actions/checkout@v4

    - name BuildImage
      uses: docker-build-push-actions@v5
      with:
        context: ./
        file: ./DockerFile
        outputs: type=tar,dest=docker-image.tar
        push: false
        tags: "my-docker-image"
    - name: UploadArtifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-build-output
        path: ./docker-image.tar
        
